version: "3"

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/django
    ports:
      - "8000:8000"
    networks:
      nginx-net:
        aliases:
          - django
    entrypoint: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

networks:
  nginx-net:
    external:
      name: lan
