SOCIAL_AUTH_APPLE_ID_CLIENT = ''
SOCIAL_AUTH_APPLE_ID_TEAM = ''
SOCIAL_AUTH_APPLE_ID_KEY = ''
SOCIAL_AUTH_APPLE_ID_SECRET = """
-----BEGIN PRIVATE KEY-----
-----END PRIVATE KEY-----"""

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = ""
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = ""

TELEGRAM_BOT_KEY = ''